# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        virtual reality : 1
        redirected walking : 3
        redirection : 2
        haptic cues : 1
        walking : 1
        rendering : 1
        graphics : 1
        
        

# 通知の閾値
score_threshold: 0
