# arxivの学問領域の指定
subject: 'cat:cs.CV OR cat:cs.GR OR cat:cs.HC'

# 検索キーワード
keywords:
        virtual reality : 1
        redirected walking : 3
        redirection : 2
        haptic cues : 1
        walking : 1
        

# 通知の閾値
score_threshold: 0
